services:
  vite:
    build:
      context: ./infra/dev/vite
    ports:
      - 5173:5173
    command: sh -c "npm install && npm run dev"
    volumes:
      - ./app:/var/www/app

  fastify:
    build:
      context: ./infra/dev/fastify
    ports:
      - 3000:3000
    command: sh -c "yarn && yarn dev"
    volumes:
      - ./api:/var/www/api

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: uno
      MARIADB_ROOT_PASSWORD: toto44
    ports:
      - 3306:3306
    volumes:
      - ./infra/dev/volumes/mariadb:/var/lib/mysql:Z

  mailcatcher:
    restart: on-failure
    image: schickling/mailcatcher
    ports: [ 1025, 1080:1080 ]